"""Update StockRating DimCompany

Revision ID: 3335952e0fd5
Revises: 4f75ca2e382c
Create Date: 2025-04-04 23:05:47.901260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3335952e0fd5'
down_revision: Union[str, None] = '4f75ca2e382c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dim_Company', sa.Column('StockRating', sa.DECIMAL(precision=2, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dim_Company', 'StockRating')
    # ### end Alembic commands ###
