"""Update DataType For Value

Revision ID: 4b06eed8f07b
Revises: 06588cc9fe5c
Create Date: 2025-04-04 23:50:22.024996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b06eed8f07b'
down_revision: Union[str, None] = '06588cc9fe5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dim_Ratio', 'Description')
    op.alter_column('Fact_FinancialRatios', 'Value',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Fact_FinancialRatios', 'Value',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=15, scale=4),
               existing_nullable=True)
    op.add_column('Dim_Ratio', sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
