"""Initial migration

Revision ID: 4f75ca2e382c
Revises: 
Create Date: 2025-04-04 13:50:27.919664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f75ca2e382c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dim_Company',
    sa.Column('StockKey', sa.Integer(), nullable=False),
    sa.Column('StockSymbol', sa.String(length=10), nullable=True),
    sa.Column('CompanyName', sa.String(length=100), nullable=True),
    sa.Column('ShortName', sa.String(length=50), nullable=True),
    sa.Column('Industry', sa.String(length=30), nullable=True),
    sa.Column('CompanyType', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('StockKey')
    )
    op.create_table('Dim_Ratio',
    sa.Column('RatioKey', sa.Integer(), nullable=False),
    sa.Column('RatioName', sa.String(length=50), nullable=True),
    sa.Column('Unit', sa.String(length=20), nullable=True),
    sa.Column('RatioType', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('RatioKey')
    )
    op.create_table('Dim_Time',
    sa.Column('TimeKey', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Quarter', sa.Integer(), nullable=True),
    sa.Column('Month', sa.Integer(), nullable=True),
    sa.Column('Week', sa.Integer(), nullable=True),
    sa.Column('Day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('TimeKey')
    )
    op.create_table('Fact_FinancialRatios',
    sa.Column('TimeKey', sa.Integer(), nullable=False),
    sa.Column('StockKey', sa.Integer(), nullable=False),
    sa.Column('RatioKey', sa.Integer(), nullable=False),
    sa.Column('Value', sa.DECIMAL(precision=15, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['RatioKey'], ['Dim_Ratio.RatioKey'], ),
    sa.ForeignKeyConstraint(['StockKey'], ['Dim_Company.StockKey'], ),
    sa.ForeignKeyConstraint(['TimeKey'], ['Dim_Time.TimeKey'], ),
    sa.PrimaryKeyConstraint('TimeKey', 'StockKey', 'RatioKey')
    )
    op.create_table('Fact_StockPrice',
    sa.Column('TimeKey', sa.Integer(), nullable=False),
    sa.Column('StockKey', sa.Integer(), nullable=False),
    sa.Column('Open', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('High', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('Low', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('Close', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('Volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['StockKey'], ['Dim_Company.StockKey'], ),
    sa.ForeignKeyConstraint(['TimeKey'], ['Dim_Time.TimeKey'], ),
    sa.PrimaryKeyConstraint('TimeKey', 'StockKey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Fact_StockPrice')
    op.drop_table('Fact_FinancialRatios')
    op.drop_table('Dim_Time')
    op.drop_table('Dim_Ratio')
    op.drop_table('Dim_Company')
    # ### end Alembic commands ###
