"""Update DataType DimCompany

Revision ID: 70ba82ae3517
Revises: 4b06eed8f07b
Create Date: 2025-04-05 01:00:27.318904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ba82ae3517'
down_revision: Union[str, None] = '4b06eed8f07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Dim_Company', 'StockRating',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Dim_Company', 'StockRating',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
